# Writing figures and the generated tex. Nothing here decides anything; it only
# formats what the panels and the statistics already computed.

save_fig <- function(plot, name, width, height) {
  ggplot2::ggsave(file.path("figs", "out", paste0(name, ".pdf")), plot,
                  width = width, height = height, units = "in", device = cairo_pdf)
  invisible(NULL)
}

# Signed quantities are set in maths mode. Two reasons: a text hyphen is not a
# minus sign, and TeX is allowed to break a line after one, which puts the digits
# of a negative number on the next line without its sign.
fmt <- function(x, digits = 2) {
  out <- formatC(x, format = "f", digits = digits)
  ifelse(x < 0, paste0("$", out, "$"), out)
}
signed <- function(x, digits = 1) sprintf(paste0("$%+.", digits, "f$"), x)
pct <- function(x, digits = 1) formatC(100 * x, format = "f", digits = digits)

# A p-value from an exact test on a handful of discordant pairs is a dyadic
# rational, not a measurement. Printing it to a fixed number of decimals would
# either round distinct values together or imply a precision the test does not
# have, so small ones are set as a power of ten and the rest to three places.
pval <- function(x, digits = 3) {
  if (x >= 10^(-digits)) return(formatC(x, format = "f", digits = digits))
  exponent <- floor(log10(x))
  sprintf("$%.1f \\times 10^{%d}$", x / 10^exponent, as.integer(exponent))
}

# A count of gradings is an integer and is printed as a word up to the point
# where words stop being easier to read than digits. One and two are the whole
# subject of this paper, so they are never rendered as bare numerals in prose.
count_word <- function(n) {
  words <- c("one", "two", "three", "four", "five", "six", "seven", "eight",
             "nine", "ten", "eleven", "twelve", "thirteen", "fourteen",
             "fifteen", "sixteen", "seventeen", "eighteen", "nineteen", "twenty")
  if (n >= 1 && n <= length(words)) words[[n]] else as.character(n)
}

macro <- function(name, value) sprintf("\\newcommand{\\%s}{%s}", name, value)

GENERATED_HEADER <- "% Generated by the figure script from hash-bound evidence. Do not hand-edit."

write_generated <- function(lines, name) {
  writeLines(c(GENERATED_HEADER, lines), file.path("tex", name))
  invisible(NULL)
}
